Ext.define('Admin.model.so.edit', {
    extend: 'Ext.data.Model',
    fields: [
        'isView',
        'notrx', 
        'tanggal', 
        'noref', 
        'pelanggan',
        'idbarang',
        'barang',
        'sales',        
        'akunwo',
        'qty',
        'qty_min',
        'satuan',
        'refalamat', 
        'tglbayar', 
        'termin', 
        'jthtempo', 
        {name: 'tunai', type: 'bool'},
        'matauang', 
        'kurs', 
        {name: 'pajak', type: 'bool'},
        {name: 'includepajak', type: 'bool'},
        'alamat', 
        'kirim', 
        'ket', 
        'typepelanggan', 
        {name: 'dariso', type: 'bool'},
        {name: 'darifaktur', type: 'bool'},
        {name: 'daripengiriman', type: 'bool'},
        {name: 'tampilbarang', type: 'bool'},
        'idnopeng',
        'nofaktur', 
        'def_extradisk', 
        'extradisk', 
        'def_totalum', 
        'totalum',
        'subtotal',
        'totbiaya',
        'bayar',
        'statusretur',
        
        'keterangan',
        'gdasal', 
        'gdtujuan', 
        'status',
        'bentuk',
        {name: 'draft', type: 'bool'},
        {name: 'uangmukacek', type: 'bool'},
        {name: 'close', type: 'bool'},
        {name: 'lock', type: 'bool'},

        'akunpeny',
        'akundp',
        'kas',
        'cabang',
        'meja',
        
        'kodewo',
        'tanggalwo',
        'akunwo',
        'statuswo',
        'totalwo',
        'tipero',
        'akun',
        {name: 'pbayar', type: 'bool'},
        'pengunjung'
    ]
});