Ext.define('Admin.model.tree.Task', {
    extend: 'Ext.data.Model',
    fields: [{
        name: 'add',
        type: 'bool'
    }, {
        name: 'idbarang',
        type: 'string'
    }, {
        name: 'barang',
        type: 'string'
    }, {
        name: 'sn',
        type: 'string'
    }, {
        name: 'ukuran',
        type: 'string'
    }, {
        name: 'warna',
        type: 'string'
    }, {
        name: 'expire',
        type: 'string'
    }, {
        name: 'harga',
        type: 'string'
    }, {
        name: 'qty',
        type: 'string'
    }, {
        name: 'pengali',
        type: 'string'
    }, {
        name: 'produksi',
        type: 'string'
    }, {
        name: 'unit',
        type: 'string'
    }, {
        name: 'idakunwo',
        type: 'string'
    }, {
        name: 'akunwo',
        type: 'string'
    }, {
        name: 'idgudangtujuan',
        type: 'string'
    }, {
        name: 'gudangtujuan',
        type: 'string'
    }, {
        name: 'idgudang',
        type: 'string'
    }, {
        name: 'gudang',
        type: 'string'
    }, {
        name: 'idgudangpatokan',
        type: 'string'
    }, {
        name: 'gudangpatokan',
        type: 'string'
    }, {
        name: 'tipeInv',
        type: 'string'
    }, {
        name: 'tipeInv_1',
        type: 'string'
    }, {
        name: 'tipeInv_2',
        type: 'string'
    }, {
        name: 'level',
        type: 'int'
    }, {
        name: 'nosumber',
        type: 'string'
    }, {
        name: 'total',
        type: 'string'
    }]
}); 