Ext.define('Admin.model.kasir.edit', {
    extend: 'Ext.data.Model',
    fields: [
        'idsesikasir',
        'iduser',
        'kas',
        'saldoawal',
        'tglmulai',
        'shift',
        'tgltutup',
        'jam',
        'menit',
        'status',
        'tglmulai_1',
        'shift_1',
        'iduser_1',
        'jumlahTamu',
        'totalTransaksi',
        'subTotal',
        'pajak',
        'total',
        'tunai',
        'diskon',
        'voucher',
        'refund',
        'debit',
        'void',
        'infosaldoawal',
        'infototaltransaksi',
        'infosaldoakhir']
//        'idsesikasir',
//        'iduser',
//        'kas',
//        'saldoawal',
//        'tglmulai',
//        'shift',
//        'tgltutup',
//        'jam',
//        'menit',
//        'status',
//        'infosaldoawal',
//        'tunai',
//        'infototalkembalian',
//        'infosaldoakhir']
});